# -*- coding: utf-8 -*-
"""wordcount_mapper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YNG9uavKLe0hsAGxKWqRSyIjjjAGEI-c
"""

#!/usr/bin/env python   

#-------------------------------------------------------------------
#this code will input a line of text and give output <word, 1>
#-------------------------------------------------------------------

#import python module with system functions
import sys

#read input file
for line in sys.stdin:
#-----------------------------------
#sys.stdin call 'sys' to read a line from standard input, line is a string object
#e.x: 'MapReduce is cool' 
# ---------------------------------
    line = line.strip()  #strip remove leading and trailing space in the sentence 
    keys = line.split()  #split the sentence by space
    for key in keys:     #a for loop through the list of keys
        value = 1        
        print('{0}\t{1}'.format(key, value) ) #the {} is replaced by 0th,1st items in format list
                            #also, note that the Hadoop default is 'tab' separates key from the value