# -*- coding: utf-8 -*-
"""Join1_mapper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yCn7xzj8hfwwZT0GyGYH_fNP2fNMIxW3
"""

#!/usr/bin/env python   

import sys

#load data from system standard
for line sys.stdin:
  line = line.strip() #clean leading and trailing space
  key_value = line.split(',') #split table by key and value
  key_in = key_value[0].split() #assign key to key_in variable
  value_in = key_value[1] #assign value to value_in variable

  #check if line from table a or b. If from table a it will have more than 1 elemen in key_in
  if len(key_in)>= 2:
    date = key_in[0]
    word = key_in[1]
    value_out = date+' '+value_in
    print('{0}\t{1}'.format(word, value_out)) #print for line from table a
  else:
    print('{0}\t{1}'.format(word, value_in)) #print for line from table B